INSERT INTO `items` (name, label) VALUES
	('brolly', 'Parapluie'),
	('kitpic', 'Kit de Pic Nic'),
	('ball', 'Grosse balle de foot'),
    ('bong', 'Bang'),
	('mask_swim', 'Masque de plongé' ),
	('sandwich', 'Sandwich'),
	('condom', 'Préservatif Souillé'),
	('magazine', 'Magasine Playboy'),
	('kalilinux', 'Kali Linux'),
	('notepad', 'Bloc Note'),
	('rose', 'Rose'),
	('bulletproof', 'Gilet par balle'),
	('tatgun', 'Dermographe'),
	('sandwich', 'Sandwich'),
	('exta'), 	'Extasie'),
	('orange'),	'Orange'),
	('grape'), 'Raisin'),
	('orangejus'), 'Jus d'orange'),
	('grapesjus'), 'Jus de raisin),

;
